lesson:
  states:
    - started
    - paused
    - finished
  transitions:
    - name: pause
      routes:
        - from: started
          to: paused
          who: [student, teacher]
    - name: answer
      routes:
        - from: started
          to: started
          who: [student]
    - name: start
      routes:
        - from: paused
          to: started
          who: [student, teacher]
    - name: finish
      routes:
        - from: paused
          to: finished
          who: [student]
        - from: started
          to: finished
          who: [student]